#include "k5-int.h"
#include "int-proto.h"
#include "fast.h"


/*
 * Implements S4U2Self, by which a service can request a ticket to
 * itself on behalf of an arbitrary principal.
 */

enum s4u2self_state {
    STATE_BEGIN,
    STATE_GET_TGT_TO_CLIENT_REALM,
    STATE_CHASE_BACK_REFERRALS_TO_SELF,
    STATE_COMPLETE
};

struct _krb5_s4u2s_creds_context {
    enum s4u2self_state state; /* What we should do with the next reply */

    k5_tkt_creds_in_data in;    /* Caller-provided initialization data */

    krb5_creds *referral_tgts[KRB5_REFERRAL_MAXHOPS];
    unsigned int referral_tgts_count;

    krb5_pa_s4u_x509_user s4u_user;
    k5_pacb_fn build_pa_s4u_cb;
    void *build_pa_s4u_data;

    struct {
        krb5_principal req_server;  /* The requested server name (storage) */
        krb5_creds tgs_in_creds;    /* Input credentials of request (alias) */
        krb5_timestamp timestamp;   /* Timestamp of request */
        krb5_int32 nonce;           /* Nonce of request */
        int kdcopt;                 /* KDC options of request */
        krb5_keyblock *subkey;      /* subkey of request */
        struct krb5int_fast_request_state *fast_state;
        krb5_pa_data **in_padata;
        krb5_data previous_request; /* Encoded request (for TCP retransmission) */
    } request;

    krb5_creds *reply_creds;    /* Creds from TGS reply */
    krb5_pa_data **reply_padata;
    krb5_pa_data **reply_enc_padata;
};

static krb5_error_code
make_pa_for_user_checksum(krb5_context context,
                          krb5_keyblock *key,
                          krb5_pa_for_user *req,
                          krb5_checksum *cksum)
{
    krb5_error_code code;
    int i;
    char *p;
    krb5_data data;

    data.length = 4;
    for (i = 0; i < req->user->length; i++)
        data.length += req->user->data[i].length;
    data.length += req->user->realm.length;
    data.length += req->auth_package.length;

    p = data.data = malloc(data.length);
    if (data.data == NULL)
        return ENOMEM;

    p[0] = (req->user->type >> 0) & 0xFF;
    p[1] = (req->user->type >> 8) & 0xFF;
    p[2] = (req->user->type >> 16) & 0xFF;
    p[3] = (req->user->type >> 24) & 0xFF;
    p += 4;

    for (i = 0; i < req->user->length; i++) {
        if (req->user->data[i].length > 0)
            memcpy(p, req->user->data[i].data, req->user->data[i].length);
        p += req->user->data[i].length;
    }

    if (req->user->realm.length > 0)
        memcpy(p, req->user->realm.data, req->user->realm.length);
    p += req->user->realm.length;

    if (req->auth_package.length > 0)
        memcpy(p, req->auth_package.data, req->auth_package.length);

    /* Per spec, use hmac-md5 checksum regardless of key type. */
    code = krb5_c_make_checksum(context, CKSUMTYPE_HMAC_MD5_ARCFOUR, key,
                                KRB5_KEYUSAGE_APP_DATA_CKSUM, &data,
                                cksum);

    free(data.data);

    return code;
}

static krb5_error_code
build_pa_for_user(krb5_context context,
                  krb5_creds *tgt,
                  krb5_s4u_userid *userid,
                  krb5_pa_data **out_padata)
{
    krb5_error_code code;
    krb5_pa_data *padata;
    krb5_pa_for_user for_user;
    krb5_data *for_user_data = NULL;
    char package[] = "Kerberos";

    if (userid->user == NULL)
        return EINVAL;

    memset(&for_user, 0, sizeof(for_user));
    for_user.user = userid->user;
    for_user.auth_package.data = package;
    for_user.auth_package.length = sizeof(package) - 1;

    code = make_pa_for_user_checksum(context, &tgt->keyblock,
                                     &for_user, &for_user.cksum);
    if (code != 0)
        goto cleanup;

    code = encode_krb5_pa_for_user(&for_user, &for_user_data);
    if (code != 0)
        goto cleanup;

    padata = malloc(sizeof(*padata));
    if (padata == NULL) {
        code = ENOMEM;
        goto cleanup;
    }

    padata->magic = KV5M_PA_DATA;
    padata->pa_type = KRB5_PADATA_FOR_USER;
    padata->length = for_user_data->length;
    padata->contents = (krb5_octet *)for_user_data->data;

    free(for_user_data);
    for_user_data = NULL;

    *out_padata = padata;

cleanup:
    if (for_user.cksum.contents != NULL)
        krb5_free_checksum_contents(context, &for_user.cksum);
    krb5_free_data(context, for_user_data);

    return code;
}

/*
 * This function is invoked by krb5int_make_tgs_request_ext() just before the
 * request is encoded; it gives us access to the nonce and subkey without
 * requiring them to be generated by the caller.
 */
static krb5_error_code
build_pa_s4u_x509_user(krb5_context context,
                       krb5_keyblock *subkey,
                       krb5_kdc_req *tgsreq,
                       void *gcvt_data)
{
    krb5_error_code code;
    krb5_pa_s4u_x509_user *s4u_user = (krb5_pa_s4u_x509_user *)gcvt_data;
    krb5_data *data = NULL;
    krb5_cksumtype cksumtype;
    int i;

    assert(s4u_user->cksum.contents == NULL);

    s4u_user->user_id.nonce = tgsreq->nonce;

    code = encode_krb5_s4u_userid(&s4u_user->user_id, &data);
    if (code != 0)
        goto cleanup;

    /* [MS-SFU] 2.2.2: unusual to say the least, but enc_padata secures it */
    if (subkey->enctype == ENCTYPE_ARCFOUR_HMAC ||
        subkey->enctype == ENCTYPE_ARCFOUR_HMAC_EXP) {
        cksumtype = CKSUMTYPE_RSA_MD4;
    } else {
        code = krb5int_c_mandatory_cksumtype(context, subkey->enctype,
                                             &cksumtype);
    }
    if (code != 0)
        goto cleanup;

    code = krb5_c_make_checksum(context, cksumtype, subkey,
                                KRB5_KEYUSAGE_PA_S4U_X509_USER_REQUEST, data,
                                &s4u_user->cksum);
    if (code != 0)
        goto cleanup;

    krb5_free_data(context, data);
    data = NULL;

    code = encode_krb5_pa_s4u_x509_user(s4u_user, &data);
    if (code != 0)
        goto cleanup;

    /* Find the empty PA-S4U-X509-USER element placed in the TGS request padata
     * XXX by krb5_get_self_cred_from_kdc() and replace it with the encoding. */
    assert(tgsreq->padata != NULL);
    for (i = 0; tgsreq->padata[i] != NULL; i++) {
        if (tgsreq->padata[i]->pa_type == KRB5_PADATA_S4U_X509_USER)
            break;
    }
    assert(tgsreq->padata[i] != NULL);
    free(tgsreq->padata[i]->contents);
    tgsreq->padata[i]->length = data->length;
    tgsreq->padata[i]->contents = (krb5_octet *)data->data;
    free(data);
    data = NULL;

cleanup:
    if (code != 0 && s4u_user->cksum.contents != NULL) {
        krb5_free_checksum_contents(context, &s4u_user->cksum);
        s4u_user->cksum.contents = NULL;
    }
    krb5_free_data(context, data);

    return code;
}

/*
 * Validate the S4U2Self padata in the KDC reply.  If update_req_user is true
 * and the KDC sent S4U-X509-USER padata, replace req_s4u_user->user_id.user
 * with the checksum-protected client name from the KDC.  If update_req_user is
 * false, verify that the client name has not changed.
 */
static krb5_error_code
verify_s4u2self_reply(krb5_context context,
                      krb5_keyblock *subkey,
                      krb5_pa_s4u_x509_user *req_s4u_user,
                      krb5_pa_data **rep_padata,
                      krb5_pa_data **enc_padata,
                      krb5_boolean update_req_user)
{
    krb5_error_code code;
    krb5_pa_data *rep_s4u_padata, *enc_s4u_padata;
    krb5_pa_s4u_x509_user *rep_s4u_user = NULL;
    krb5_data data, *datap = NULL;
    krb5_keyusage usage;
    krb5_boolean valid;
    krb5_boolean not_newer;

    assert(req_s4u_user != NULL);

    switch (subkey->enctype) {
    case ENCTYPE_DES3_CBC_SHA1:
    case ENCTYPE_DES3_CBC_RAW:
    case ENCTYPE_ARCFOUR_HMAC:
    case ENCTYPE_ARCFOUR_HMAC_EXP :
        not_newer = TRUE;
        break;
    default:
        not_newer = FALSE;
        break;
    }

    enc_s4u_padata = krb5int_find_pa_data(context,
                                          enc_padata,
                                          KRB5_PADATA_S4U_X509_USER);

    /* XXX this will break newer enctypes with a MIT 1.7 KDC */
    rep_s4u_padata = krb5int_find_pa_data(context,
                                          rep_padata,
                                          KRB5_PADATA_S4U_X509_USER);
    if (rep_s4u_padata == NULL) {
        if (not_newer == FALSE || enc_s4u_padata != NULL)
            return KRB5_KDCREP_MODIFIED;
        else
            return 0;
    }

    data.length = rep_s4u_padata->length;
    data.data = (char *)rep_s4u_padata->contents;

    code = decode_krb5_pa_s4u_x509_user(&data, &rep_s4u_user);
    if (code != 0)
        goto cleanup;

    if (rep_s4u_user->user_id.nonce != req_s4u_user->user_id.nonce) {
        code = KRB5_KDCREP_MODIFIED;
        goto cleanup;
    }

    code = encode_krb5_s4u_userid(&rep_s4u_user->user_id, &datap);
    if (code != 0)
        goto cleanup;

    if (rep_s4u_user->user_id.options & KRB5_S4U_OPTS_USE_REPLY_KEY_USAGE)
        usage = KRB5_KEYUSAGE_PA_S4U_X509_USER_REPLY;
    else
        usage = KRB5_KEYUSAGE_PA_S4U_X509_USER_REQUEST;

    code = krb5_c_verify_checksum(context, subkey, usage, datap,
                                  &rep_s4u_user->cksum, &valid);
    if (code != 0)
        goto cleanup;
    if (valid == FALSE) {
        code = KRB5_KDCREP_MODIFIED;
        goto cleanup;
    }

    if (rep_s4u_user->user_id.user == NULL ||
        rep_s4u_user->user_id.user->length == 0) {
        code = KRB5_KDCREP_MODIFIED;
        goto cleanup;
    }

    if (update_req_user) {
        krb5_free_principal(context, req_s4u_user->user_id.user);
        req_s4u_user->user_id.user = NULL;
        code = krb5_copy_principal(context, rep_s4u_user->user_id.user,
                                   &req_s4u_user->user_id.user);
        if (code != 0)
            goto cleanup;
    } else if (!krb5_principal_compare(context, rep_s4u_user->user_id.user,
                                       req_s4u_user->user_id.user)) {
        code = KRB5_KDCREP_MODIFIED;
        goto cleanup;
    }

    /*
     * KDCs that support KRB5_S4U_OPTS_USE_REPLY_KEY_USAGE also return
     * S4U enc_padata for older (pre-AES) encryption types only.
     */
    if (not_newer) {
        if (enc_s4u_padata == NULL) {
            if (rep_s4u_user->user_id.options &
                KRB5_S4U_OPTS_USE_REPLY_KEY_USAGE) {
                code = KRB5_KDCREP_MODIFIED;
                goto cleanup;
            }
        } else {
            if (enc_s4u_padata->length !=
                req_s4u_user->cksum.length + rep_s4u_user->cksum.length) {
                code = KRB5_KDCREP_MODIFIED;
                goto cleanup;
            }
            if (memcmp(enc_s4u_padata->contents,
                       req_s4u_user->cksum.contents,
                       req_s4u_user->cksum.length) ||
                memcmp(&enc_s4u_padata->contents[req_s4u_user->cksum.length],
                       rep_s4u_user->cksum.contents,
                       rep_s4u_user->cksum.length)) {
                code = KRB5_KDCREP_MODIFIED;
                goto cleanup;
            }
        }
    } else if (!krb5_c_is_keyed_cksum(rep_s4u_user->cksum.checksum_type)) {
        code = KRB5KRB_AP_ERR_INAPP_CKSUM;
        goto cleanup;
    }

cleanup:
    krb5_free_pa_s4u_x509_user(context, rep_s4u_user);
    krb5_free_data(context, datap);

    return code;
}

/* State Functions */

static krb5_error_code
complete(krb5_context context, krb5_s4u2s_creds_context ctx)
{
    //TRACE_TKT_CREDS_COMPLETE(context, ctx->reply_creds->server);

    /* Put the requested server principal in the output creds. */
    krb5_free_principal(context, ctx->reply_creds->server);
    ctx->reply_creds->server = ctx->in->req_server;
    ctx->in->req_server = NULL;

    /* Note the authdata we asked for in the output creds. */
    ctx->reply_creds->authdata = ctx->in->authdata;
    ctx->in->authdata = NULL;

    if (!(ctx->in->req_options & KRB5_GC_NO_STORE)) {
        /* Try to cache the credential. */
        (void) krb5_cc_store_cred(context, ctx->in->ccache, ctx->reply_creds);
    }

    ctx->state = STATE_COMPLETE;
    return 0;
}

inline static krb5_creds *request_tgt(krb5_s4u2s_creds_context ctx)
{
    return ctx->referral_tgts[ctx->referral_tgts_count -1];
}

static krb5_error_code
make_s4u2self_padata(krb5_context context, krb5_creds *tgt,
                     krb5_pa_s4u_x509_user *s4u_user,
                     krb5_pa_data ***padata)
{
    krb5_error_code code;
    krb5_pa_data **in_padata = NULL;

    *padata = NULL;

    in_padata = k5calloc(3, sizeof(krb5_pa_data *), &code);
    if (in_padata == NULL)
       return code;

    in_padata[0] = k5alloc(sizeof(krb5_pa_data), &code);
    if (in_padata[0] == NULL) {
        krb5_free_pa_data(context, in_padata);
        return code;
    }

    in_padata[0]->magic = KV5M_PA_DATA;
    in_padata[0]->pa_type = KRB5_PADATA_S4U_X509_USER;
    in_padata[0]->length = 0;
    in_padata[0]->contents = NULL;

    if (s4u_user->user_id.user->length) {
        code = build_pa_for_user(context, tgt, &s4u_user->user_id,
                                 &in_padata[1]);
        if (code != 0) {
            krb5_free_pa_data(context, in_padata);
            return code;
        }
    }

    *padata = in_padata;
    return 0;
}

static krb5_error_code
make_request(krb5_context context, krb5_s4u2s_creds_context ctx,
                int extra_options)
{
    krb5_error_code code;
    krb5_data request = empty_data();

    ctx->request.kdcopt = extra_options | ctx->in->req_kdcopt |
        FLAGS2OPTS(request_tgt(ctx)->ticket_flags);

    /* Create a new FAST state structure to store this request's armor key. */
    krb5int_fast_free_state(context, ctx->request.fast_state);
    ctx->request.fast_state = NULL;
    code = krb5int_fast_make_state(context, &ctx->request.fast_state);
    if (code)
        return code;

    krb5_free_keyblock(context, ctx->request.subkey);
    ctx->request.subkey = NULL;
    code = k5_make_tgs_req(context, ctx->request.fast_state,
                           request_tgt(ctx), ctx->request.kdcopt,
                           request_tgt(ctx)->addresses,
                           ctx->request.in_padata,
                           &ctx->request.tgs_in_creds,
                           ctx->build_pa_s4u_cb, ctx->build_pa_s4u_data,
                           &request, &ctx->request.timestamp,
                           &ctx->request.nonce, &ctx->request.subkey);
    if (code)
        return code;

    krb5_free_data_contents(context, &ctx->request.previous_request);
    ctx->request.previous_request = request;

    return 0;
}

static krb5_error_code
make_initial_s4u2s_request(krb5_context context, krb5_s4u2s_creds_context ctx)
{
    krb5_error_code code;

    krb5_free_principal(context, ctx->request.req_server);
    ctx->request.req_server = NULL;

    code = krb5_copy_principal(context, ctx->in->in_creds->server,
                               &ctx->request.req_server);
    if (code)
        return code;

    ctx->request.tgs_in_creds = *ctx->in->in_creds;
    ctx->request.tgs_in_creds.server = ctx->request.req_server;

    code = krb5_copy_principal(context, ctx->in->impersonate,
                               &ctx->s4u_user.user_id.user);
    if (code)
        return code;

    ctx->s4u_user.user_id.subject_cert = ctx->in->impersonate_cert;
    ctx->s4u_user.user_id.options = KRB5_S4U_OPTS_USE_REPLY_KEY_USAGE;

    ctx->build_pa_s4u_cb = build_pa_s4u_x509_user;
    ctx->build_pa_s4u_data = &ctx->s4u_user;

    code = make_s4u2self_padata(context, request_tgt(ctx),
                                &ctx->s4u_user, &ctx->request.in_padata);
    if (code)
        return code;

    code = make_request(context, ctx, 0);
    if (code)
        return code;

    ctx->state = STATE_CHASE_BACK_REFERRALS_TO_SELF;
    return 0;
}

static krb5_error_code
begin(krb5_context context, krb5_s4u2s_creds_context ctx)
{
    krb5_error_code code;

    if (krb5_is_referral_realm(&ctx->in->in_creds->server->realm)) {
        krb5_free_data_contents(context, &ctx->in->in_creds->server->realm);
        code = krb5int_copy_data_contents(context,
                                          &ctx->in->impersonate->realm,
                                          &ctx->in->in_creds->server->realm);
        if (code)
            return code;
    }

    code = k5_get_cached_local_tgt(context, ctx->in->in_creds->client, 0,
                                   ctx->in->ccache, &ctx->referral_tgts[0]);
    if (code)
        return code;

    ctx->referral_tgts_count = 1;

    if (krb5_realm_compare(context, ctx->in->in_creds->client,
                           ctx->in->impersonate))
        return make_initial_s4u2s_request(context, ctx);

    /* XXX check if we got cached foreign tgt ? */

    /* First, acquire a TGT to the user's realm. */
    code = krb5int_tgtname(context, &ctx->in->impersonate->realm,
                           &ctx->in->in_creds->client->realm,
                           &ctx->request.req_server);
    if (code != 0)
        return code;

    ctx->request.tgs_in_creds.client = ctx->in->in_creds->client;
    ctx->request.tgs_in_creds.server = ctx->request.req_server;

    code = make_request(context, ctx, 0);
    if (code)
        return code;

    ctx->state = STATE_GET_TGT_TO_CLIENT_REALM;
    return 0;
}

/* Return an error if server is present in referral_list. */
static krb5_error_code
check_referral_path(krb5_context context, krb5_principal server,
                    krb5_creds **referral_list, int referral_count)
{
    int i;

    for (i = 0; i < referral_count; i++) {
        if (krb5_principal_compare(context, server, referral_list[i]->server))
            return KRB5_KDC_UNREACH;
    }
    return 0;
}

static krb5_error_code
set_principal_realm(krb5_context context, krb5_principal princ,
                    krb5_data *realm)
{
    krb5_free_data_contents(context, &princ->realm);
    return krb5int_copy_data_contents(context, realm, &princ->realm);
}

static krb5_error_code
follow_referral(krb5_context context, krb5_s4u2s_creds_context ctx)
{
    krb5_error_code code;

    if (ctx->referral_tgts_count == KRB5_REFERRAL_MAXHOPS)
        return KRB5_KDCREP_MODIFIED;

    if (!IS_TGS_PRINC(ctx->reply_creds->server))
        return KRB5KRB_AP_WRONG_PRINC;

    if (data_eq(request_tgt(ctx)->server->data[1],
                ctx->reply_creds->server->data[1]))
        return KRB5_ERR_HOST_REALM_UNKNOWN;

    code = check_referral_path(context, ctx->reply_creds->server,
                               ctx->referral_tgts, ctx->referral_tgts_count);
    if (code)
        return code;

    ctx->referral_tgts[ctx->referral_tgts_count] = ctx->reply_creds;
    ctx->reply_creds = NULL;
    ctx->referral_tgts_count++;

    code = set_principal_realm(context, ctx->request.req_server,
                               &request_tgt(ctx)->server->data[1]);
    if (code)
        return code;

    return make_request(context, ctx, 0);
}

static krb5_error_code
get_tgt_to_client_realm(krb5_context context, krb5_s4u2s_creds_context ctx)
{
    int i;

    /* XXX save in cache and use ? */
    if (!krb5_principal_compare_any_realm(context, ctx->request.req_server,
                                          ctx->reply_creds->server))
        return follow_referral(context, ctx);

    for (i = 0; i < KRB5_REFERRAL_MAXHOPS; i++) {
        krb5_free_creds(context, ctx->referral_tgts[i]);
        ctx->referral_tgts[i] = NULL;
    }

    ctx->referral_tgts[0] = ctx->reply_creds;
    ctx->reply_creds = NULL;
    ctx->referral_tgts_count = 1;

    return make_initial_s4u2s_request(context, ctx);
}

static krb5_error_code
chase_back_referrals_to_self(krb5_context context, krb5_s4u2s_creds_context ctx)
{
    krb5_error_code code;

    /* Update s4u_user.user_id.user if this is the initial request to the
     * client realm; otherwise verify that it doesn't change. */
    code = verify_s4u2self_reply(context, ctx->request.subkey, &ctx->s4u_user,
                                 ctx->reply_padata, ctx->reply_enc_padata,
                                 ctx->referral_tgts_count == 1);
    if (code)
        return code;

    if (krb5_principal_compare_any_realm(context, ctx->request.req_server,
                                         ctx->reply_creds->server)) {
        /* Verify that the unprotected client name in the reply matches the
         * checksum-protected one from the client realm's KDC padata. */
        if (!krb5_principal_compare(context, ctx->reply_creds->client,
                                    ctx->s4u_user.user_id.user))
            return KRB5_KDCREP_MODIFIED;

        return complete(context, ctx);
    }

    /* Only include a cert in the initial request to the client realm. */
    ctx->s4u_user.user_id.subject_cert = empty_data();

    krb5_free_checksum_contents(context, &ctx->s4u_user.cksum);
    krb5_free_pa_data(context, ctx->request.in_padata);
    ctx->request.in_padata = NULL;

    code = make_s4u2self_padata(context, request_tgt(ctx),
                                &ctx->s4u_user, &ctx->request.in_padata);
    if (code)
        return code;
    
    return follow_referral(context, ctx);
}

/* Decode and decrypt a TGS reply, and set the reply_code or return error. */
static krb5_error_code
get_creds_from_tgs_reply(krb5_context context, krb5_s4u2s_creds_context ctx,
                         krb5_data *reply)
{
    krb5_error_code code;

    krb5_free_creds(context, ctx->reply_creds);
    ctx->reply_creds = NULL;

    krb5_free_pa_data(context, ctx->reply_padata);
    ctx->reply_padata = NULL;

    krb5_free_pa_data(context, ctx->reply_enc_padata);
    ctx->reply_enc_padata = NULL;

    code = krb5int_process_tgs_reply(context, ctx->request.fast_state,
                                     reply, request_tgt(ctx),
                                     ctx->request.kdcopt,
                                     request_tgt(ctx)->addresses,
                                     ctx->request.in_padata,
                                     &ctx->request.tgs_in_creds,
                                     ctx->request.timestamp,
                                     ctx->request.nonce, ctx->request.subkey,
                                     &ctx->reply_padata,
                                     &ctx->reply_enc_padata,
                                     &ctx->reply_creds);

    return code;
}

/*
 * Fill in the caller out, realm, and flags output variables.  out is filled in
 * with ctx->previous_request, which the caller should set, and realm is filled
 * in with the realm of ctx->cur_tgt.
 */
static krb5_error_code
set_caller_request(krb5_context context, krb5_s4u2s_creds_context ctx,
                   krb5_data *caller_out, krb5_data *caller_realm)
{
    krb5_error_code code;
    const krb5_data *req = &ctx->request.previous_request;
    const krb5_data *realm = &request_tgt(ctx)->server->data[1];
    krb5_data out_copy = empty_data(), realm_copy = empty_data();

    code = krb5int_copy_data_contents(context, req, &out_copy);
    if (code != 0)
        return code;
    code = krb5int_copy_data_contents(context, realm, &realm_copy);
    if (code != 0)
        return code;

    *caller_out = out_copy;
    *caller_realm = realm_copy;
    return 0;
}

/***** API functions *****/

krb5_error_code
k5_gc_s4u2s_init(krb5_context context, k5_tkt_creds_in_data in_data,
              krb5_s4u2s_creds_context *out_ctx)
{
    krb5_error_code code;
    krb5_s4u2s_creds_context ctx;

    *out_ctx = NULL;

    //TRACE_TKT_CREDS(context, in_data->in_creds, in_data->ccache);
    ctx = k5alloc(sizeof(*ctx), &code);
    if (ctx == NULL)
        return code;

    ctx->state = STATE_BEGIN;

    ctx->in = in_data;

    *out_ctx = ctx;
    ctx = NULL;

    return 0;
}

krb5_error_code
k5_gc_s4u2s_step(krb5_context context, krb5_s4u2s_creds_context ctx,
                 krb5_data *in, krb5_data *out, krb5_data *realm,
                 krb5_boolean *need_continue, krb5_creds **reply_creds)
{
    krb5_error_code code;
    krb5_boolean no_input = (in == NULL || in->length == 0);

    *out = empty_data();
    *realm = empty_data();
    *need_continue = FALSE;
    *reply_creds = NULL;

    /* We should receive an empty input on the first step only, and should not
     * get called after completion. */
    if (no_input != (ctx->state == STATE_BEGIN) ||
        ctx->state == STATE_COMPLETE)
        return EINVAL;

    if (!no_input) {
        /* Convert the input token into a credential and store it in ctx. */
        code = get_creds_from_tgs_reply(context, ctx, in);
        if (code == KRB5KRB_ERR_RESPONSE_TOO_BIG) {
            code = set_caller_request(context, ctx, out, realm);
            if (code != 0)
                return code;
            /* Instruct the caller to re-send the request with TCP. */
            *need_continue = TRUE;
            return KRB5KRB_ERR_RESPONSE_TOO_BIG;
        }
        if (code != 0)
            return code;
    }

    if (ctx->state == STATE_BEGIN)
        code = begin(context, ctx);
    else if (ctx->state == STATE_GET_TGT_TO_CLIENT_REALM)
        code = get_tgt_to_client_realm(context, ctx);
    else if (ctx->state == STATE_CHASE_BACK_REFERRALS_TO_SELF)
        code = chase_back_referrals_to_self(context, ctx);
    else
        code = EINVAL;

    if (code != 0)
        return code;

    if (ctx->state != STATE_COMPLETE) {
        code = set_caller_request(context, ctx, out, realm);
        if (code)
            return code;
        *need_continue = TRUE;
    } else {
        *reply_creds = ctx->reply_creds;
        ctx->reply_creds = NULL;
    }

    return 0;
}

void
k5_gc_s4u2s_free(krb5_context context, krb5_s4u2s_creds_context ctx)
{
    int i;

    if (ctx == NULL)
        return;
    for (i = 0; i < KRB5_REFERRAL_MAXHOPS; i++) {
        krb5_free_creds(context, ctx->referral_tgts[i]);
    }
    k5_tkt_creds_in_data_free(context, ctx->in);
    krb5int_fast_free_state(context, ctx->request.fast_state);
    krb5_free_principal(context, ctx->request.req_server);
    krb5_free_keyblock(context, ctx->request.subkey);
    krb5_free_data_contents(context, &ctx->request.previous_request);
    krb5_free_principal(context, ctx->s4u_user.user_id.user);
    krb5_free_creds(context, ctx->reply_creds);
    krb5_free_pa_data(context, ctx->request.in_padata);
    krb5_free_pa_data(context, ctx->reply_padata);
    krb5_free_pa_data(context, ctx->reply_enc_padata);
    krb5_free_checksum_contents(context, &ctx->s4u_user.cksum);
    free(ctx);
}
